[build.processing]
  skip_processing = false
[build.processing.css]
  minify = true
[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """\
      base-uri 'self'; \
      block-all-mixed-content; \
      child-src 'none'; \
      default-src 'self'; \
      form-action 'none'; \
      frame-ancestors 'none'; \
      frame-src 'none'; \
      img-src 'self'; \
      media-src 'self'; \
      object-src 'none'; \
      script-src 'none'; \
      style-src 'self'; \
      worker-src 'none';\
    """
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[redirects]]
  from   = "https://refresh-dc-org.netlify.com/*"
  to     = "https://refresh-dc.org/:splat"
  status = 301
  force  = true
