source: ./src
destination: ./public

host: 0.0.0.0

future: true

title: Refresh DC
description: Refresh DC is a group of Web Designers, Web Developers, and other New Media Professionals gathering to create a community based in Washington, DC.

permalink: /:categories/:year/:title

defaults:
  - scope:
      path: events
      type: posts
    values:
      layout: event

assets:
  defaults:
    css:
      integrity: false
    img:
      integrity: false
    js:
      integrity: false
  sources:
    - _assets/stylesheets
