title: Refresh DC
description: Refresh DC is a group of Web Designers, Web Developers, and other New Media Professionals gathering to create a community based in Washington, DC.
url: https://refresh-dc.org
license:
  name: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/
source:
  name: GitHub
  url: https://github.com/jgarber623/refresh-dc.org
